url: https://gorskisolutions.com
enforce_ssl: gorskisolutions.com
baseurl:

exclude: [Gemfile, Gemfile.lock]

# Site settings
title: Konrad Górski Solutions
email: konradgrski@gmail.com
description: "Konrad Górski Solutions: Mobile Software Services"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: "009688"
  secondary: ffc107
  secondary-dark: ffa000
  nav-bar: ffc107

# Build settings
markdown: kramdown
permalink: pretty

kramdown:
  input: GFM


# Try merging all the css again and use native jekyll/sass minification
sass:
  sass_dir: _sass
  style: compressed


# GH-pages supported plugins
plugins:
  - jekyll-feed
  - jekyll-mentions
  - jemoji
  - jekyll-redirect-from
  - jekyll-sitemap


# jekyll-compress-html
# https://github.com/penibelst/jekyll-compress-html
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: []
  blanklines: false
  profile: false
  startings: [html, head, body]
